#!/usr/bin/env python3
"""
Generate Rust colormap lookup tables from matplotlib colormaps.

Usage:
    .venv/bin/python viewarr/generate_colormaps.py

This generates viewarr/src/colormap_luts.rs with 256-entry RGB lookup tables.
"""

import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path


# Colormaps to export
COLORMAPS = [
    "inferno",
    "magma", 
    "RdBu",
    "RdYlBu",
]


def generate_lut(cmap_name: str) -> list[tuple[int, int, int]]:
    """Generate a 256-entry RGB lookup table for a matplotlib colormap."""
    cmap = plt.get_cmap(cmap_name)
    lut = []
    for i in range(256):
        rgba = cmap(i / 255.0)
        r = int(round(rgba[0] * 255))
        g = int(round(rgba[1] * 255))
        b = int(round(rgba[2] * 255))
        lut.append((r, g, b))
    return lut


def format_rust_array(name: str, lut: list[tuple[int, int, int]]) -> str:
    """Format a LUT as a Rust const array."""
    lines = [f"pub const {name}: [[u8; 3]; 256] = ["]
    for i, (r, g, b) in enumerate(lut):
        lines.append(f"    [{r:3}, {g:3}, {b:3}],")
    lines.append("];")
    return "\n".join(lines)


def main():
    output_path = Path(__file__).parent / "src" / "colormap_luts.rs"
    
    lines = [
        "// Auto-generated by generate_colormaps.py",
        "// Do not edit manually - regenerate with:",
        "//   .venv/bin/python viewarr/generate_colormaps.py",
        "",
        "#![allow(clippy::unreadable_literal)]",
        "",
    ]
    
    for cmap_name in COLORMAPS:
        const_name = f"{cmap_name.upper()}_LUT"
        lut = generate_lut(cmap_name)
        lines.append(format_rust_array(const_name, lut))
        lines.append("")
        print(f"Generated {const_name} ({len(lut)} entries)")
    
    output_path.write_text("\n".join(lines))
    print(f"\nWrote {output_path}")


if __name__ == "__main__":
    main()
